AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  quadball-processing

  Sample SAM Template for quadball-processing

Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  StatsheetParserFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: statsheet_parser/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Layers:
        - arn:aws:lambda:us-west-2:765351438123:layer:statsheet:28 # TODO: figure out some way to do #latest lmao 
    
