name: "lambdas-deploy-workflow"

on:
  push:
    branches:
      - main    
    paths: 
      - lambdas/**
jobs:
  deploy-packages:
    name: "Deploy Packages"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.ADMIN_AWS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.ADMIN_AWS_SECRET_KEY }}
      AWS_REGION: us-west-2

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Package snowflake
        run: bash shell/package-external-lambda-layer.sh snowflake lambdas/layers/snowflake