name: "Terraform-Plan"

on:
  pull-request:
    branches:
      - main

jobs:
  terraform-plan:
    name: "Terraform Plan"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.ADMIN_AWS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.ADMIN_AWS_SECRET_KEY }}
      AWS_REGION: us-west-2

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      

      - name: Terraform Init
        id: init
        run: cd infrastructure && terraform init
      
      - name: Terraform plan
        id: plan
        run: cd infrastructure && terraform plan