name: "webapp-deploy"

on: 
  push:
    branches:
      - main
    paths: 
      - app/**
jobs:
  deploy-webapp:
    name: "Deploy webapp"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.ADMIN_AWS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.ADMIN_AWS_SECRET_KEY }}
      AWS_REGION: us-west-2

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy webapp
        run: bash shell/deploy-app.sh